export const SAVE_PEOPLE = 'SAVE_PEOPLE';
export const GET_EPISODES_SUCCESS = 'GET_EPISODES_SUCCESS';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_STARSHIPS_SUCCESS = 'GET_STARSHIPS_SUCCESS';
