export const GET_EPISODES_SUCCESS = 'GET_EPISODES_SUCCESS';
export type GET_EPISODES_SUCCESS = typeof GET_EPISODES_SUCCESS;

export const GET_EPISODES_FAIL = 'GET_EPISODES_FAIL';
export type GET_EPISODES_FAIL = typeof GET_EPISODES_FAIL;