import { GET_EPISODES_SUCCESS, GET_EPISODES_FAIL } from './anime-episodes-types';
import { SAVE_PEOPLE, GET_PEOPLE_SUCCESS, GET_PEOPLE, GET_PEOPLE_FAIL } from './sw-people-types';
import { GET_STARSHIPS_SUCCESS, GET_STARSHIPS_FAIL, GET_STARSHIPS } from './sw-starships-types';

export {
  GET_EPISODES_SUCCESS,
  GET_EPISODES_FAIL,

  SAVE_PEOPLE,
  GET_PEOPLE_SUCCESS,
  GET_PEOPLE_FAIL,
  GET_PEOPLE,

  GET_STARSHIPS_SUCCESS,
  GET_STARSHIPS_FAIL,
  GET_STARSHIPS
}
