import { GET_EPISODES_SUCCESS } from './episodes';
import { GET_STARSHIPS_SUCCESS, SAVE_PEOPLE, GET_PEOPLE_SUCCESS } from './sw';

export {
  GET_EPISODES_SUCCESS,
  SAVE_PEOPLE,
  GET_PEOPLE_SUCCESS,
  GET_STARSHIPS_SUCCESS
}
