export const GET_STARSHIPS = 'GET_STARSHIPS';
export type GET_STARSHIPS = typeof GET_STARSHIPS

export const GET_STARSHIPS_SUCCESS = 'GET_STARSHIPS_SUCCESS';
export type GET_STARSHIPS_SUCCESS = typeof GET_STARSHIPS_SUCCESS;

export const GET_STARSHIPS_FAIL = 'GET_STARSHIPS_FAIL';
export type GET_STARSHIPS_FAIL = typeof GET_STARSHIPS_FAIL;